export const ADD_GROCERY = 'ADD_GROCERY';
export const GROCERY_LOADING ='GROCERY_LOADING';
export const GROCERY_FAILED = 'GROCERY_FAILED';
export const BASKET_EMPTY = 'BASKET_EMPTY';
export const ADD_BASKET_ITEM = 'ADD_BASKET_ITEM';
export const REMOVE_BASKET_ITEM = 'REMOVE_BASKET_ITEM';
export const REMOVE_BASKET = 'REMOVE_BASKET';
export const DECREMENT_BASKET_ITEM = 'DECREMENT_BASKET_ITEM';